on:
  push:
    branches:
    - dev
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - run: ls
    - name: Build
      run: dotnet build src/CalendarAnalyser/CalendarAnalyser.Core/CalendarAnalyser.Core.csproj --configuration Release
    - name: Test
      run: dotnet test src/CalendarAnalyser/CalendarAnalyser.Core.Tests/CalendarAnalyser.Core.Tests.csproj --configuration Release --no-build