on:
  push:
    branches:
    - dev

env:
  VERSION: 1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set Version variable
      env:
        SHA: ${{ github.sha }}
      run: echo "VERSION=$VERSION-${SHA::7}" >> $GITHUB_ENV
    - run: echo "Building for version $VERSION"
    - name: Build
      run: dotnet build src/CalendarAnalyser/CalendarAnalyser.Core/CalendarAnalyser.Core.csproj --configuration Release
    - name: Test
      run: dotnet test src/CalendarAnalyser/CalendarAnalyser.Core.Tests/CalendarAnalyser.Core.Tests.csproj --configuration Release --no-build