on:
  push:
    branches:
    - dev
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: dotnet build ./src/CalendarAnalyser/CalendarAnalyser.Core/Calendar.Analyser.Core.csproj --configuration Release
    - name: Test
      run: dotnet test ./src/CalendarAnalyser/CalendarAnalyser.Core.Tests/Calendar.Analyser.Core.Tests.csproj --configuration Release --no-build